# Generated by Django 3.2.7 on 2021-09-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado')),
                ('state_short', models.CharField(blank=True, max_length=3, null=True, verbose_name='Código')),
                ('postal_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='País')),
                ('code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Código')),
                ('timezone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Zona Horaria')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.city')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
    ]
